### ISSUE TITLE
ChatSupport Systems commands

### ISSUE THREAD

**Issue by St3v3a** [cheetz/THP3_Updates#1]
Hi,
The link to the lab.txt is not working, had a look through your repositories but cannot find it?

https://github.com/cheetz/THP-ChatSupportSystem/blog/master/lab.txt

Thks

Steve

**Comment by cheetz** [comment]
Sorry, it's up and located here: https://github.com/cheetz/THP-ChatSupportSystem/blob/master/lab.txt

**Comment by St3v3a** [comment]
Hi Peter,

That’s great thanks and really enjoying the book!

Regards

Steve

Steve Atkinson
