### ISSUE TITLE
CSK VM

### ISSUE THREAD

**Issue by 4p0ll0** [cheetz/THP3_Updates#10]
I have been unable to find any details about how to get the CSK Chat VM running. The only setting I am changing from default is putting it in Host-Only mode. In VirtualBox it only shows the loopback interface. In VMWare it is showing lo and 'ens33', which I am assuming is how it is intended to work. Is the VM supposed to be able to run in either? I wasn't sure how much detail to provide here so let me know whatever you need.

**Comment by cheetz** [comment]
Hey, yup, it's only supported in VMWare and when you boot it up, you should see an IP on the screen (for ens33).  Do you see an IP?  If not, can you also try to do a NAT instead of Host Only? 

If you see an IP, you should be able to hit it on port 3000.

**Comment by 4p0ll0** [comment]
Yea it seems like its working normally in VMWare. I just wish I had thought to try this 2 months ago when I was stuck in VirtualBox. Thanks for responding quickly, I guess I'll just stick with VMWare..

**Comment by cheetz** [comment]
Ah, correct me if I'm wrong here (and of course sorry for any trouble), but I thought I mentioned that everything needs to be done in vmware in the book (I might be wrong here).  Actually, all the other VMs except the Web one will work in virtual box.  I had to do some funky stuff for the Web VM to get it all stable.  Again, sorry and hope you're enjoying the ebook.

-pk

**Comment by 4p0ll0** [comment]
Yea I just checked, you did say VMware but I guess it didn't occur to me that it could work with one and not the other. The book is great, I learned a ton without even getting into anything technical yet.
