### ISSUE TITLE
chat support vuln vm is not showing the ip address

### ISSUE THREAD

**Issue by Shahidkhanofficial** [cheetz/THP3_Updates#2]
hello sir,
               i have downloaded the chat support system from " http://thehackerplaybook.com/get.php?type=csk-web " when i am running this vm, it's only showing the loopback address (not ip address) and when am trying to open localhost/127.0.0.1:3000 its giving me error

**Comment by cheetz** [comment]
Sorry to hear but wanted to get a little more info:  
- First, just to make sure, you are running this vm in VMWare, right?   
- If so, when you boot up the VM, you should see the IP address on the login screen.  Are you saying you only see the loopback?  If so, something is wrong and most likely an interface issue.  If it only has loopback, you won't be able to access it from your THP-Kali VM. 

-Peter

**Comment by Shahidkhanofficial** [comment]
thanks for the reply sir :)
actually am running that vm on virtualbox
and is it necessary to run that vm in vmware and access that vm from thp-kali VM?
am accessing it from my physical pc (parrot os)

**Comment by cheetz** [comment]
Nope, you don't have to do it from the THP-Kali VM, but you probably do have to run the csk-web from VMWare to get it to work properly out of the box.

**Comment by Shahidkhanofficial** [comment]
ok i will set up vmware sir :) will update you.....
thank you

**Comment by cheetz** [comment]
Haven't heard back, so closing this ticket.  Let me know if it's still a problem.

**Comment by icamys** [comment]
I can confirm that when running the image in VirtualBox on the boot screen is shown only loopback interface, however when running in VMWare both ethernet and loopback interfaces are shown and the app is accessible.
