### ISSUE TITLE
slurp

### ISSUE THREAD

**Issue by leog4488** [cheetz/THP3_Updates#3]
your book places step to about S3 bucket enumeration using slurp:
* cd /opt/slurp 
i dont see slurp in opt directory im using your VM THP3-Lethal-2018
i tried cloning slurp from github.com address you provided to /go/src
it created a slurp folder but then when i tried running ./slurp it said directory not found
for the life of me i couldnt get it to run

**Comment by cheetz** [comment]
Hey leogg4488,

Odd that it was missing.  Here's the temporary fix you can do until I upload a new VM on the THP3-Lethal-2018

- git clone https://github.com/bbb31/slurp.git /opt/slurp && cd /opt/slurp && cp /root/go/bin/slurp /opt/slurp/

- ./slurp domain -t cyberspacekittens.com

Thanks,
Peter

**Comment by cheetz** [comment]
I also updated all the VMs and put slurp back in the /opt/slurp folder.  Let me know if something doesn't work.
