### ISSUE TITLE
Customer System Support VM

### ISSUE THREAD

**Issue by prvnkumark** [cheetz/THP3_Updates#6]
Hi Peter,

I am enjoying "THP3" , thank you for writing such a wonderful book and sharing your knowledge.

I am struggling to get IP address from CSK-Web VM , I tried VM in Nat and Bridge mode , i can see only loopback IP address. 

PS: Using virtual box

**Comment by cheetz** [comment]
Hey Prvnkumark,

Thanks for the kind words.  At this time, I only support VMWare.  So if you can, please try and use VMWare Workstation/Player (use the free trial or player).  The reason I only support VMware is that any changes have to go through a lot of testing and everything is validated in VMware.  Let me know if that fixes it.

Thanks,
Peter Kim

**Comment by prvnkumark** [comment]
Hi Peter,

Thank you for writing back, I was able to run VM successfully using VMware Player.
