### ISSUE TITLE
slurp link not working

### ISSUE THREAD

**Issue by c60cb859** [cheetz/THP3_Updates#7]
The link to the slurp github is not wroking

**Comment by thpbKurlee** [comment]
Same here, looks like bbb31 has deleted all repositories.

**Comment by BakkaBr** [comment]
From the book "As mentioned before, when you edit or delete a file in Github, everything is tracked.
Fortunately for Red Teamers, many people forget about this feature. Therefore, we
often see people put sensitive information into Github, delete it, and not realize it's still
there! Let's see if we can find some of these gems."

**Comment by cheetz** [comment]
Odd, I'm not sure why he removed it, but for the mean time, Slurp is on the KALI-THP VM under /opt/slurp.  I'm not sure if I can host his code if he took it down.  

-pk

**Comment by cheetz** [comment]
I'm going to close this for now as it exists on the THP VM and can be found on archive.org: https://archive.org/details/github.com-bbb31-slurp_-_2017-12-05_23-19-32.
